apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-tenant
resources:
  - github.com/minio/operator/resources/base/
  - tenant-config.yaml
  - storage-user.yaml
  - tenant.yaml