apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-
  namespace: workflows # invoke workflow in argo namespace where workflow service account lives
spec:
  serviceAccountName: workflow
  volumes:
  - name: regcred
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  - name: sshkey
    secret:
      secretName: git-ssh
  - name: github-access
    secret:
      secretName: github-access
      items:
        - key: token
          path: token
  workflowTemplateRef:
    name: cluster-workflow-template-ci
    clusterScope: true
