--

apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow
subjects:
- kind: ServiceAccount
  name: workflow

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"