apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: task-tracker-app
  labels:
    app: task-tracker-app
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - task-tracker-app.local
  http:
  - name: primary
    route:
    - destination:
        host: task-tracker-app # target kubernetes service
        port:
          number: 80
      weight: 100

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
     - "*" 