apiVersion: eks.mlops-playground.com/v1alpha1
kind: EKSCluster
metadata:
  name: mlops-playground
  annotations:
    argocd.argoproj.io/sync-wave: "300"   
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true    
  namespace: default
spec:
  parameters:
    nodeSize: small
  compositionSelector:
    matchLabels:
      provider: default
      service: eks
  writeConnectionSecretToRef:
    namespace: default
    name: cluster-staging