apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: my-db
  namespace: default
spec:
  parameters:
    storageGB: 30
  compositionSelector:
    matchLabels:
      provider: default
      vpc: default
  writeConnectionSecretToRef:
    name: db-conn