apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true

    s3:
      bucket: my-bucket
      endpoint:   argo-artifacts.default:9000        
      insecure: true                  
      accessKeySecret:               
        name: my-minio-cred
        key: xxxxx
      secretKeySecret:                
        name: my-minio-cred
        key: xxxxx           
      useSDKCreds: false