apiVersion: v1
data:
  artifactRepository: |
    s3:
      bucket: my-bucket
      # keyFormat: prefix/in/bucket     #optional
      endpoint: argo-artifacts.default:9000        #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
      insecure: true                  #omit for S3/GCS. Needed when minio runs without TLS
      accessKeySecret:                #omit if accessing via AWS IAM
        name: my-minio-cred
        key: o8HXEn7KIAFV9qmzRqwk
      secretKeySecret:                #omit if accessing via AWS IAM
        name: my-minio-cred
        key: SL70gUV5YY0kF8pBdc39szhrsZAS9826JGa2PjeQ
      useSDKCreds: true               #tells argo to use AWS SDK's default provider chain, enable for things like IRSA support
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  creationTimestamp: "2022-09-21T14:36:06Z"
  name: workflow-controller-configmap
  namespace: argo
  resourceVersion: "114065"
  uid: 746fbe06-1d18-4c91-8175-2ef1c60e6d10