apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  hub: docker.io/istio
  tag: 1.1.6
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        istio: ingressgateway
      k8s:
        overlays:
          - kind: Service
            name: istio-ingressgateway
            patches:
              # Select list item by value
              - path: spec.type
                value: "NodePort" 
              - path: metadata.annotations
                value: |
                    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
                    alb.ingress.kubernetes.io/healthcheck-port: 30218