kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31923
    hostPort: 8080
  image: kindest/node:v1.23.0

  # if we want to map files on our local machine to directories inside the container
  # - role:  worker
  #   extraMounts:
  #   - hostPath: ./data
  #     containerPath: /tmp/data

  # - role:  worker
  #   extraMounts:
  #   - hostPath: ./data
  #     containerPath: /tmp/data
