apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-ssh
  namespace: workflows
spec:
  encryptedData:
    key: AgCUZb5WjXHK9bEI3LZKzfJJkOwvyxlPbQVtKlFDXf4IkFNatdI6KuS57Jczr8KO/gtPCvoP7ElVw0cNGLUypVPBpGqo+aAutfoUzOwKPOqLauikCh35iI/Gwp1EWRQCtMrmsAnV7KnvVtaX3Kj93u7YjwQMB0QBpzs6DEPetv9X2YtLm6OsvkLSHVpMKbDfWNizeJcxswyBlgw7eP60uTDEho8aMU2u05lqEG9IKEd21MWFAlIo0S5dwzxCiTNiwcDhlLch3nYYVw2prj6diKmGhSUv6zR3yIC5zxm81hWB97N3Z4ln40+bbv08RtmukNHh5p0pg1tmlG5o3L6x5ACYXhz+1tdj2TQGNz6dyQcWtAi2EaudiL6duAcizk/3/MH1Dsiu5FGGDRsneRjDp0ehbztZY/9omSyPmfx+dtPG+wHI9fg6fRJBjRghxeIGF8GyAqDWeNxt6Y3Mm+/wyS8wXZhghZgOE9EpB0lUHPqDPp5ZU65UFfoIspZCOn0ftb/yZ/VRTgEuX8mWmlBzR3gopEZyYAiO6dXpYyKk4TXJW3IB9H8RqfWgiFKcJxQwLBL117TOHYciePFOiGCXmBpFYFn4hqHzkkMaVhiIQStn4ZXa9YnOTLzsV0QTiLX7Z7vlonW6CShx0PyGtnfnK2m/C+UK0L9YFe9cjHwYoLgeoBXTbx4+seuVvi70JC9wTMaACskXUJX5/AhsGFTVQlxS3s6/71hiJK6nPto8ur/z21holjPV/I5pkI/rcw+leBHvKpab9NkSb17LHMT1D/NsuYRzTmf0PfakOLVdn+eNN4pmHKDYTke9Aj3Q5gzKIRyW11pPAniMvcrBIfkGQJ7fh05C6CvYx9oUd2rjQEp8xksqEfM24Mv4a07i7QudVpdBkidA4OFcbzxu9uNPeLs5na2y3Iu+L22/z5ABEjvg/T8HZZpAHx6VnLC6w+bX4sM++jxM74DvQdUXbt5GhgR6EEV2jiIcB5XsCsjQQWApER3FuXwCih+TAX9E+uxdiAWq60A0Bx8QFIGbJ9vPrIkqZyuLnBhZvLtVSACnFbfMbiLfutkZUW319CSu+r62mMtsc03dgwXqZ4nKMklCeWoKovkp8+YMUwjr0xuHYh/Zxkl5Af+5mDCemeQAZiHrItz0ngWCJ3ZB8rNRbPIACY6c8eHiZlOhVWsm2wnefcUI/n6yp8MxscN6EOTKTn0rEs9n03gdeGks5ysG8K00L/+XUaqoO3pRzsbW84Q=
  template:
    metadata:
      creationTimestamp: null
      name: git-ssh
      namespace: workflows

