apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-ssh
  namespace: workflows
spec:
  encryptedData:
    key: AgAirRNZ/UdV+4ePHFPhCoKeMeiLfWaK5LZ0ZTFKCeuXkx+ZPuQsQs/20TKnSa1sFwGz5Cf36KRTe1/v8eFozLBIj9GrFrRRPpjbw/e2rT8eKRwMvjLNItER2k0aaaXI9loUA6pv8AHd5YmozdAsflRopzdtMeNeMyNbW1ACcA2fHGeEzL9XjfRdt7bb1L4Ib2UnpsJMVlAF4PXx16MO+TI7KK5/Tkf3qOJP+VQ1GmyeGd+i1kJ1qNvsaaKl3TWGomaRcHodpcUt1QhtjCOJXhn2l4dWUfHaRHH2qeQLMoIBv2NtkErHHIlS7n1O9uUgEXtmKHw6LQaW4/RXsttOksCd4/etZZj6uc1Xv2j2eEqCRYL6yy4tNNgqqnp4ZK1NwxmZHQc89Cn1nKA+OUuqRtx2xH78odQM7D2kEKHKhXeLrtIPKi/WSZI41bC1SZJAsQ/kIm7j9puLxKO3cC0iIv7QofulMbNvRVwKFiP8NxYHT7/Ld9/FRqhCbytmQ2jeF7Euvra+mj/1TzEl7EWQlBfbmjmW+kV8bCiEMkJOlCFjG3F5GHzJf1E7iMlFCgrFAJDuzi5tHO0XKistzQqvXDFMBPs3vD/Hv0/cDPkRJvLmHliqMfII3QDj/GPHHJgzALL63pKokk4Czp7h6kd2OxwAPeg6dETYx3lStOpt+ZH06bydwsb69Z2O59aCVJr5+G9VWYa0HCzfboBfR2mLnbrNX9TsfCQbFr0Ju9P9jzB+wRl/vERP8D+9pAvopvveZdZmBSX6zdZ9zb1tMjn6MrvwzaJAWoKWjLMVZ7ZlmF/yZYK86u6TOf+C9h8wHjoPHlha3iWypYr33TOFzXeiCBSuYbGJQhLvkKSQC4p8Bxza/slXEEBPWgtqGRGyqUeRRy9q5D5RmYx1uq+u64fe4cXtPR2lCtTHMOAhEkbbJLKxokVfdNAiHf+wXjI5OaYyOVqL/fbzsBpvNzeqQS+tIwidMW18hNMzVnsQXNhPkk8Uzch8KUbqWJZAGmaUDeHAgISprsJUlubDEwWzCEj+HD7L68/RzS57IylH6hlwqWgFw+x9TL7OQRQ+gApXNBZObwasZAWXV9LGBMT8K2NYPf/CVsGAl3dnjnGimqh6TIcsIqQYG5+RvkgDKzk7hwCV0rViVVilJkBl0bSv3RPPP5/uCvtvNJ5g4+RqwY3g15u1ALBTJ2+UVds7dVYj/0Almp4YEAJeLXX/Br6RwKkTZ+u4N1+6jI3YSl5IbEk=
  template:
    metadata:
      creationTimestamp: null
      name: git-ssh
      namespace: workflows

