apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-ssh
  namespace: workflows
spec:
  encryptedData:
    key: AgAWzeNk5GBl4fC2+WFFS2VcQd+vl/HHsyjFKpaE3Woth1P0mOZsfsiNQRAkyh+bxUIzfybG8epmhcJX6AJ0fdrYwDoNz4WQYQGCzHMVt9JCBgSxka1x5qKFsd2yo8VnRttsTZ2nN9aTIeIqDcZXMRFHOOjjehgEMiHaJzhAB4BSyVdaXTW84c8LEiS/gI9OayxNzJIgv6JaO0jM86zo9UR2fAOw+aqJHk8f2+10Hp3mADHfMQJ605NOxhbXPTmIkKOjc04LHencigR1sCnIQMDZcMIS7VOdc0UMKUse4SkO+T4HangR3uE7feBqdijfXoD0yQozY2/ZQNMR/7biFUaWN2lHRwcVEg+sLdT3Sxexq+xpVGJjZaZjJmq97Gm2S5x9+NmFaDJoETAg4euBBSooqZLANMT9UBmJNenEoNOE55flC8w5SYzxp4ko14o5TRJRQZ70rHEH0RqSX+Zsj+cJ9m+ai5FJwQQVe3nYotAGY6x4owt5ZTawhNPAwJHZDNLdifNkU0mA6ZIYj0gbx6lrw6n+PvtawkvMPTWVsa2L+UkvPBpNs0FlHBw6uXlh0GCBMltfCVCq4FG3hgLNT3guyKPS/bFaOhMr+lyoot3edE18tPvEbeeOvxEueSOH+QPQMtsmv1mafNQd4FuDlt9Emp09dxjVFSc9Tw3mQbY1MLDUi0+DpzZYw6GA7zqoPRmmXT5CTYdZnXnqb64v1Vr7Byp8k6HOT/W7RY8uLyKkpW5PNnNOuWyhY89RVU28rDK2MzhiiyQ/f28Z6jF525W4bsm6rQvUJJDO53b//EvLLs5Z4jCztq5nkepyPmMc+XEFmaR/sIP8xuw5Yh0Q64sPoTlU7WMfJ+NcFb7/HEa87c5r5zBtYXR3UTjIQlw4K/90uzIf81u2yY7dJTJURCNm/n+3TrJ8urlvsaJNdr8HYca/WMQlNghZrKtjWDYQovlbNvenEJDjcBzDWP5tN0BzBFjFj7ZSXPb+bGqXe8KTrB3CSfiH/JgTdoK5W+CZqfl2Gi6VkRjBnFB5aJUD2Iqc3SI+xjYQriwiUCTjmkNpk2DGu5ZYPo+qEMbgQ/mMovepAH5jSPH35dS1j0eNzJg6AgiIFCuzqDmrOicpgtjG4/FIG+0FQV+alG+Qd92bYjhBua2LPtNdg8n9B+kiqiaAmH4XOsHdSoltKbx0NOxb6nAYEEsZ4q1uKAaGsPxciovDHYxtT08q9YI0dfU2n6MftgtXgYYLNvp7Zx0=
  template:
    metadata:
      creationTimestamp: null
      name: git-ssh
      namespace: workflows

