apiVersion: eks.mlops-playground.com/v1alpha1
kind: EKSCluster
metadata:
  name: mlops-playground
  annotations:
  namespace: default
spec:
  parameters:
    nodeSize: small
  compositionSelector:
    matchLabels:
      provider: default
      service: eks
  writeConnectionSecretToRef:
    namespace: default
    name: cluster-staging