apiVersion: eks.mlops-playground.com/v1alpha1
kind: EKSCluster
metadata:
  name: cluster-staging
spec:
  id: team-foxy
  parameters:
    nodeSize: small
  compositionSelector:
    matchLabels:
      provider: default
      service: eks
  writeConnectionSecretToRef:
    name: aws-kubeconfig

---

# apiVersion: eks.mlops-playground.com/v1alpha1
# kind: EKSCluster
# metadata:
#   name: cluster-production
#   annotations:
#   namespace: default
# spec:
#   parameters:
#     nodeSize: small
#   compositionSelector:
#     matchLabels:
#       provider: default
#       service: eks
#   writeConnectionSecretToRef:
#     namespace: default
#     name: cluster-production