apiVersion: devopstoolkitseries.com/v1alpha1
kind: App
metadata:
  name: devops-toolkit
  labels:
    app-owner: vfarcic
spec:
  id: devops-toolkit
  compositionRef:
    name: app-frontend
  parameters:
    namespace: production
    image: foxy7887/task-tracker:v1
    host: staging.mlops-playground.com