apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume-0
  labels:
    type: local
spec:
  storageClassName: standard # this will be claimed by the local-minio/minio-s3-log-minio-s3-log-0 pod
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/export/data/0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: manual # this will be claimed by the local-minio/data0-minio-s3-pool-0-0 pod
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/export/data/1"

---