apiVersion: batch/v1
kind: Job
metadata:
  generateName: predictions-
spec:
  template:
    spec:
      containers:
      - name: predictions
        image: alpine/curl
        command: [sh, -c]
        args: 
        - |  
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"data": { "ndarray": [[1,2,3,4,5,6,7,8,9,10,11]]}}' \
          http://seldon-deployment-deploy-wine-clf-j6wp2-single-model.workflows.svc.cluster.local:8000/api/v1.0/predictions
      restartPolicy: Never
  backoffLimit: 4

