apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install.yaml
- gateway.yaml

namespace: istio-system

patchesStrategicMerge:
- patches/service.yaml
- patches/remove-pdb.yaml