apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install.yaml

namespace: istio-system

patchesStrategicMerge:
- patches/remove-pdb.yaml

patchesJson6902:
- target:
    version: v1 
    kind: Service
    name: istio-ingressgateway
    namespace: istio-system
  path: patches/ing-gw-patch.yaml