apiVersion: apps/v1
kind: Deployment
metadata:
  name: "console"
  labels:
    app: minio-console
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio-console
  template:
    metadata:
      labels:
        app: minio-console
    spec:
      serviceAccountName: console-sa

      containers:
        - name: minio-console
          image: minio/console:v0.20.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          args:
            - server
          

