apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  labels:
    app: minio-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio-operator
  template:
    metadata:
      labels:
        app: minio-operator
    spec:
      serviceAccountName: minio-operator
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 2000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - minio-operator
      containers:
        - name: minio-operator
          image: minio/operator:v4.5.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"