# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: mlflow-postgres # forward traffic on port 5432 to statefulset pods with mlflow-postgres label
  clusterIP: None
  selector:
    app: postgres
