apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    tcpKeepalive:
      time: 10s
      interval: 5s
      probes: 3
  components:
    ingressGateways:
      - enabled: true
        name: cluster-local-gateway
        label:
          app: cluster-local-gateway
          istio: cluster-local-gateway
        serviceAnnotations:
          alb.ingress.kubernetes.io/healthcheck-port: '30621'
          alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
        k8s:
          env:
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          hpaSpec:
            maxReplicas: 5
            metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: cluster-local-gateway
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          service:
            type: ClusterIP
            ports:
            - name: status-port
              port: 15020
              targetPort: 15020
              nodePort: 30621
            - name: http2
              port: 80
              targetPort: 8080

    # Disable EgressGateway
    egressGateways:
    - enabled: false
      name: istio-egressgateway