apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  serviceAccountName: workflow
  templates:
  - name: build-kaniko-git
    inputs:
      parameters:
      - name: repo_url
      - name: repo_ref
        value: refs/heads/main
      - name: repo_commit_id
        value: HEAD
      - name: container_image
      - name: container_tag
      - name: subfolder
    container:
      image: gcr.io/kaniko-project/executor:debug
      command: [/kaniko/executor]
      args:
      - --context={{inputs.parameters.repo_url}}#{{inputs.parameters.repo_ref}}#{{inputs.parameters.repo_commit_id}}
      - --context-sub-path={{inputs.parameters.subfolder}}
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker/

---


apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: promote
spec:
  serviceAccountName: workflow
  templates:
  - name: promote
    inputs:
      parameters:
      - name: subfolder
      - name: repo_owner
      - name: repo_name
      - name: image_owner
      - name: image_name
      - name: tag
    script:
      image: foxy7887/kustomize:v2
      command: [sh]
      source: |
        set -e
        git clone https://$(cat /.github/token)@github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}
        git config --global user.email "davidmfox87@gmail.com"
        git config --global user.name "David Fox"
        cd {{inputs.parameters.repo_name}}/{{inputs.parameters.subfolder}}
        sleep 2
        echo BEFORE:
        cat kustomization.yaml
        echo AFTER:
        kustomize edit set image {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}={{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:{{inputs.parameters.tag}}
        cat kustomization.yaml
        git add kustomization.yaml
        git commit -m "Upgraded {{inputs.parameters.subfolder}}/kustomization.yaml with the tag {{inputs.parameters.tag}}"
        git push
      volumeMounts:
      - name: github-access
        mountPath: /.github/
      - name: sshkey
        readOnly: true
        # container will see /root/.ssh/id_rsa as usual:
        mountPath: /root/.ssh
      - name: known-hosts
        mountPath: /etc/ssh
