apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
spec:
  selector:
    matchLabels:
      app: mlflow-tracking-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-tracking-server
    spec:
      containers:
      - name: mlflow-tracking-server
        env:
        # "Normal" (not headless) Services are assigned a DNS A or AAAA record, 
        # depending on the IP family of the Service, for a name of the form 
        # my-svc.my-namespace.svc.cluster-domain.example. 
        # This resolves to the cluster IP of the Service.
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-svc.minio-local.svc.cluster.local/ 
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minio123"

usybox-1.default-subdomain.my-namespace.svc.cluster-domain.example