apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  # namespace will be injected by Kustomize
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
    selector:
      eventsource-name: github-webhook
  github:
    test:
      owner: davidfox87
      repository: task-tracker
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://21c5-135-84-103-250.ngrok.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
