apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAH1rjXR8L4Pg4iWpkvuZC86kHXCLyp1ICYuWueurpEcv/Ta2YhVt1ZmQpYnmwfRzlHVaRNRkX6kWHKQprwulSXewGI4Je6pW1rr/FkGKSefQKAaXeJ6DTUpgClnQCkH3+YgPITe7uCNCXA5wvH7TS3yrjTZ8Ase5Y7/fN7Rxe7bNmBzh64p+J2U7S8y2Gg9TXBIog6dbTVJRokmYoG19dwA+AqYifS30T9C+IWbkZ3Rx3GoRlRtsMQWgKvE7eXuHQq7CBlf8N0Sz9okxKmZ2s9FTFWfBA8Fa2ZViIy9Gpo0cC5ek2YCWCCMlKIcvABnbaPYfx4XQLyMu6B7/FBZCAdFwO9w+UBgmCea3ZcZ3NracFSldWNLYO6/fz1Ce+jBvahIIi3sup7mrtncBjKfqExmTraIqMxftc5t5j5KjwDL/pEqQkr/HPBBQdfUQs1zGA/BWy6rSCuCKD3kaQKWXA9X1WUcD4i7LbgRVumwG0lIaIVxR58kkLYIVA87nD4GKiG27qiDnoNkbqbRh6k4siSPC3BnL7POpU6ODlCHo3qiVtMeNJw6VdVQGY52QYZ9cRdY9Bpc0BrWCxpcKD2dhzMexr5oyZZEd+xuXPR2SFhb1OJhiCo2VgmlmKzXlAg9W7hXbQZoB1u7C+z/gTmehxAeigwRRgFOwg/hPoCuE4zJC6MheGmk66ZWgdbdUftgTvfOzhUQE4XDLnZjPeW/5kYKBM6iSlndf1X/P/N5veBPz6g+Im+2aA6CtMZc6VR
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

