apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBljzA/k2g+P6F2lYEefoKc3+PyRGm5c8uFUXruRyTylVe5IRVim6wU4ywrRNkeqEAZBIbm5OQmcKYXUQpShOSC/I63VEg4kGc0wn7YZ30ZT1fcNeHIak+Sb4GZtO9j8MMMtl61SvZv6pUTBwd9Wx4e3KJf4Lqq7hyKfMFzNbTv/EE8d4nJuSV2KlcFJ1VmZiY8hwxa+J8qO2wjG6hWHnJXeAyC13wBX3+nhF/v1PwT3d4YdBYLZNM1jddXK7RwTlk237WpB7ri2+iSKW1YOHZAsyszUqX2TKNW9pzIIi2QG9GmLyAuv7V2tyobI58DO6PT3Cp/VByy871x4yWGU05+R3M2Mdql2Ht86tjw44ZFawgK7DKAdrsAdXsFE8bOLfg/RHVOr/W2iGu/Ag8PV9uAobpT6t37DQvl5clpWBDTemzH9Eu08ZGEaMTxc9dppfRfSeTj/qOoopySsrjBQhnzE5v3IgigTI+TNNu0v8PbRCLqgnbp/0ri8BxPRZmCc6F1v5frqDxdSveqUGvH5FqjCMCgDR4yIzooheTGvgAd2+spRxOoxrSTWzYoYoK5Xx30kuXccEDFGXInt9go7Ucgb3rsNIDjmuUQlazqdHSwrjFgAwOymF67y3edTwEFLidUWbQgvkJvzm96xWX0YncVxKZDBcBr0zLh4/50BtII8qVwYevjjs4eS6QW7RErmz6ayWsJY5JC+fdEXb4jOR5MXyOCTb8xDfDfgZLboAI4csx7lc5ibPpp
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

