apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    password: AgAp6VRW4IOX0s67rOxotD5V7DHmeRwZtwTT/jFk0pxdc3G13dYVc12SBR/DXSFR9Xk3g84k/5FmklkgCI/MJ9gp0zQgaJ3vbp9p8Vq7AbNOH65rUO528bNsfP8Ms/Iq84oe4Itdh32pBrs0Lw92jbUA+yMSEdQCePxKm7c62x29tckSg8TSF8bysGjYN7Dw4AfOXiobo1IvhmjvQL0YQbET9IT2ql/vpgaZKWY4U5MxRhb9hSPO0W6zugeMSAv6kV5NMmkFusQ7wgD1D2+0Yn2Ll7jmo0o/tzS9Zp3+IuDuCCHPdqt3bpIZRlMmsNOsVkAfxGXYpOjh8mZSnuKB/AeCAXvDr7xG5usrPhNNDiQ+GmsgyW+p1bUa+1zR08+BfiGFCjqJBaTFHHmcdfehdvsrlahXyqYSThIDwWIa/bCXPz+5+Xhp6yNhdJ2JXB5HphckwPvXCwtUnrNZXN6nhfBU+ZILZ4nu9f6av0f+arridEptF4k+h9PmagrO3Ky8ZpZF+LWoaM4+R+MIiZg0835TPvwak4FcNqu1wa/CUFVB8bymh1SkfNKhR2LGV2M7oCZq2coy0lWqEJkryJcI9XBva9S6eXhcBrRKHYLELCvTT3SKY61TdA3tCPLDYlHWAv3Lyrn2aapxiQXqyWasW06KU/tEyplbEYeBQdjgoivYB37emkE9Enr6v7nONDbotAon9LDMXkGqjvUpAFsIiUWQ+fX9/Nj0+2KF339Kw/wow31FwXQ//J11
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

