apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    password: AgAKFtwmVz69z+OAXOD37wi3QB0rtKG4KgB+Zw/+EbPuPk0Y9eSbd+lmwwR+jLcw2tljXUJO4pUrRsOpz2IjbhheGvGRkmXeg3pNzz+sHMamJvv0v4W6OEL7LAOTQWwUSH3NHVEOZVlvLEmonA+SxeqIB0KiEhmNoV+MOZg0LdQkz+UIIWKBndxHs7h+ot0vOQJvaT045wlwRGXMrHztw0WmbDPuYTaro7ysZP2+Qwk/OPVVNxtN23y5k7El9HLuLie7ttH7xcfKOnQZ3PpWbziVSGKwQkd+4iR6tFmIboYq5kNhUPCj5mg0wQpIrqhjJd5622aW9T81r098j1iMejeqTcg3THxLTolfFmxnvPnupXNrLFoHG5MqvI88Xqtk3HTOLIAjy9aC190YGJtTrgOMgtiJeclhJHA8KnWDz/ETfPnl8FkbJE5w7uT7iAjK0ABUymFAU5w0+hzrZLHBr18i6rDWGxUBbP0Rapj6TYIIZqU+A+rEHDF2GkMRE0RcQ4xBVaYViX03JArirdezxVYld2PaxIlrODgVhSxCEdBdUcetym+JnuaeYsyNx+aqPVUIwE+o8zwJb4muqWoZzvIou1zHFBIpQv8Qdc1GmqPiLNDJg+h3fbcpirs1aaVgUX2Bldr/Q3ziOU/ADi7TCWefo/k5CQm+7r4gwQT3Sx/Tp0/8n257jcD3Qha1AoTLpCeomdPIRCV6dY6wQE3mc/15+liGoqiKRkG20A+T09WnBl9BeZDyyRkW
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

