apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    password: AgBTpnwWEl/ph183KXdHnemlqM2cA3p91SnBzg3vWhhhHVuFVR+Cz1184qKZgocd437GWVrJlWSqD+2p7yXkZgWgurfrzr4nN9xx061W87BxXCfUgQAFBDcvlq2S/TGxj5fwOaF8E+NKqjXbPGfClpUT9nKZlkdTCHhyq/AFkeDjapK3Yj468u9jaxuGoxcqoOYvTjfDQwgTVwTbmuEd62JKKNUSZjPNwQ657X6IjCx/MEtbeASB5vwGBoegcYsfvFjsJ5l75QD0eJAICrkhfLReitvsG9jw6BXx+riXA5FpwG3WT22/9Gp2HeKXAgQCP2K0gy5g7ImDJ5v8PZSEZBiGkLJb3W6pfLV5HIMZnOMZPj8h45WmegK9uGQ5h2qdDUOACZYTD58UCmEutNA+WXzJ7fnH4QLsfW4bNdkm6+6IDyPnEU4ih+k6O9y8maLpX/bh4qRKqGQFaAuYXBZJBk+1AQlbPFe+Nt3Y3/Iu6W4vsU8+QnaoagIFrZQPJXI2X1vVuAzrQv8edfzHfmcXVmruhmUZ9riodBuu9EYg6LZTHL2SJZrE4DIiQ2MG6IcrqTEHIpOHD1VYDy7hxVF1A3qw2Kxv5p8Vyb0QVV4lQLPGSDKJJ189Q/SV5JRNuR6YKgRSL5HhXpbPyYjuHjf9prW/nMYjZN8Aw8/pol2zJeet9Zvx6UKntjNsUDuO5CEAJm9zIQJcSYAJ4OLiQrEbvOxx9UG4ai5AmDbOakCGln7ic5b2a/cZWsIe+pyqOMTW0tfS
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

