apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBe8MNbtG55Nxvxy7ZDXwOQwVp7MHp6wdgA+NJOtQdUz2i0iLibWFVEBtjjff5/OmjO2yeqIl+bQMD3/xDG6ipcXsTI1VigiVvAfruSZs3Q9MRicBem0AeLs++gHTDlA1t3zdX7a6BIvdIXuHwlHhsA2Yv4PsFplTHtzX9hu/Ix8nwcVjphUvUx9TYHhbRiNdlIwm7ikzm8gX2zRs0VFy2zP4NlKBUdTWARoKmIKN+fJWt1wzojifeDgX7+CdLYoD1/oIaOrMbCG2Zys6gf3kVpJgKk6liqnGXlNVQlbrxiUnWl/7JShsVFKcQWzFN7526u9fJx73H1R1sIKD3ojuRKuR9DnkLCjxIzC2MAN1fHWDrubI0QcRe9+TnCC2wxNIL+ParYvt23Bg2Yyml3ri95Z7dbv/P1reoQIGfYi0ZckTI+J/R+/7gAl9DN8jTTJ4L1jSXgh3b8xwZI69q1tMDHUEKXe+rAtnShBj/jKpxrcB7r76OQqJH3J9qP8WKTOKHQKlKPidU5TNkjKQOp1UT+ISVK510+KmvHdyPw+qGJU5o5RJRkcxw0Lxcg4ZZO/R44QMZprkWOH0noH7RmZp19WsLxPsB8CrIHrLFWuXT6nmh4cntM1ndpCER5xgKQ51vAiqb1e4lLDooIvBeE8di4aYwN4caix2WNkEZemGNesJ2XasvsDzAn5E4J+AcGqJvB7bFbP2SzH7cGndN0opX2hoYpLMMZtEY7417XaGkD+B5zVz7rHbzF0dveRvDntZMks+Uer31ZLYcPjZu0BZOfJl53nlnrFFKcgQ2Sk3nPw7yhOwTcRA6IZwvZZvAjL8ok+kE=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

