apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- event-sources.yaml
- sensors.yaml
# - ingress.yaml
- github-access.yaml # sealed-secret
namespace: argo-events