
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # This is the selector for the istio ingress gateway
  servers:
  - port:
    number: 443
    name: https-443
    protocol: HTTPS
  tls:
    mode: SIMPLE
    credentialName: "tls-secret"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: task-tracker-app-virtualservice
spec:
  hosts:
  - '*'
  gateways:
  - default-gateway
  http:
  - match:
    - uri:
      prefix: /home                         # get to the ui
    - uri:
        prefix: /api/v1/tasks               # get to the nodejs backend api
    - uri:
        prefix: /api/v1/get-task-by-id       # get to the nodejs backend api
    route:
    - destination:
        host: task-tracker-app-ui.default.svc.cluster.local # virtual service must be in the same namespace as service or explicitly specify namespace
        port:
          number: 9080


