apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Manifests downloaded from:
# - github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.crds.yaml
- cert-manager.yaml

