apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCGdTl3BryhI3mwfFJxWerD1r5N3ckN44I9hP62MN78Zr6ljx7Vjs9WUWyui0PSSbWY74r8pIGBB0KzhmnwBqEDryG9IXclPX5h10dYsfj3EzsROcaDlewAoWrXLHOgOplr2OfE6P68jtjuQGIAPLCWtsh7wedi5f6zff+0KdLGmTqRdEjb8br9Vb5qzWNWPlGzA1Tp7HdcGQGUAmcqmpQ4OgckXquMhfKvmkAd5QHS2KwPA42eQZAZDLvCovBoCNFr7U0F/w5KE+9ubKSLv5jP5HsCanNsUg039qkFRFwGpRPNMOjQtQSkObLp7jC6MnzHy8Q2vavkXKV+xxrQxQCPKbW6d2Pc/cujs+EFs5SSF8ST5oqLfY6KryYWf5TMIUq565hnUXGePi7aEVw0agS+AXr6NQHOUau9TIf3Neyd9vvxPQb21oNyL2ivMhOxXhxNMfqgrJM+CwEb+3giJ5ROcTewdvetdGNVjAE2Ns/uLVHblHS8B9LSH0QvPROGlsOL4u9AiVUTnONEeVuDBGB0v+A00uN3B3Y+kLdKwIpNEXAoHRpsLnoa6gBvsShcyyAg+TdpkeN1MqRmCqyWN2hoFUcJrBuU4bsPOeDjQ3jYinltd2pclPZpd0QERh0xh0prRUr7SYqPwEkI2qpxR7tWzwApTVe8nWpGH3k4UjN9bOmPx+HeksT8fO6y5MZ0kJ8hAn6sS+RmQ0xN4F4kU6BS1ufJ4Sv40yva64FDYpS+Ph3LC3eJ8X/NUkCi7qDBgrBkC/m8t6kp9bakitIH9SgE3deTe05N4uoU+AOmomGGW0MqcfQ4n/1S5SRuXfcVi4xcSRqsKYudUVtEcTh8G3F7e9TC8g==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

