apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCMZqrGGmtSWh1MBd+W75xLpoRrDMjhRd1NYB8KUnxV6Hb3X+SUt5JRKG2Zd7RuXwXWIQKAaLyRouIt2gTOCWDPQMSWuDPqdS8rI7cy2QSEGgiv14TbQbaOnbrc60SLuMDtNaFRAI70fDNNTHnjwEuk3iXXqcynZK1JuIEweNlEomxj7srW6/f3U7gjLFYvGH7c0TLf2Sqs8hXIyq+pxUazbzh7VG9hsgh4PlBp0lUSuiKny4ZfAw6ATBvAithtTIH5AsCJwJHAMpve/bwn/K9hSI4dvf48zykmaGUUVbLn+xLj/lb1IOoUMG2ruy+x3IQh8CYLG9VUh1C+Q42eLcBkKjoPwpKe+dfBUmnuBBSeJgreMsHslsKv9/EPzcSoVEr/jw9xIGI1aqXl3n6HqtpZNGKpbdOans7rJUtHTAa9hc/JFZZHoymmF3OMKNobj8I3M7UFgcLmzA2+GfV7wB8EQw4YB5s18PWSh13/QS5vH4zlawpw6tewpuD4GdGSS+bnhK245rrhw05lOBQ+/rckzpk5LhfvkrccSwuk6jihYhjh24F4SwbDkRR0GEd278Em2s2jVibEPQtf0D6SdbIWY6z19G3NFSE3SF4kFwfUiPWC8PyM4Tb7OqGiE+s2rLra1Jr6rcG2SfNOiZVBn/WUOh+xOnJKcL8BW+N4OCUbAWB9UF3AfzTTPpsCyn2ChPki1HpGSeI6WYws4NGLIyTaY98xzXkkKTcQDga0sBzL2DDHaUh0frfj78vDqh9QfEW0NlMwFMi+sxpfZ8iVPC9a+woLIBQfQ0K3ERKVL0w5wtPz7ighPWsBCOCr4CUjZkG/W6E4MnJyrBVwqPi88cZtD6p4cA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

