apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgC5IoFUCv4scdZG0U8jqbQSUtRDnK5UPHWdS1eY3A6Z1/1rTsj6XKUDFauBry9IQDV9RE/xMh8aJJRwQMWx1eh9w9okgnS/7TUFffcdRqDgStkbvdoQCVIujJJc8Bb58JFrwxHr7XHHdXkLdNWiwP30YP+sEEBfQge/z74DkUXlUnvkkw9vfQBtm4uNevTCIGKUj2gkubT2vLt3fNng42qKWaw7YOh6mqHhWdePlZqRW1DeXUnOV/DIXrEs/nNpGExFhsKqe1l9LNgDylJ+xTSb8gG0wtqCjd+uWsHOh0k4wtI6SopJDivZ/KA5KX1PTrP++xQQPh+UX6gGnTWOfe9HLK2Rq1ohpfqB9UfKqQRDx5GMKarm24ZrNsjbF9RMRnYC6CG/GCWfQYKgX8Ufuhjxq04DHLFu/C282fj5+tlSYmArhL687o6XO59yeaA2BmFBLc+98x7hTXsZPY2A440jnIComyPW1WZacVGdeyWRZyRUR+gF3qgckdrKDhySYMvjw9U7VfK3Et2GTkfjHhPFiuIg9yvT08HnEn+gYg7yjYrr+fHR/OQonyS5ghrIprFUhFQaTmnHAlE0j0kx1GHbB0wq+IT9MXB+QTA10yJC/T9FJZCSoKE+5jYuYKdLjPjwxcQ+rrWgdr2Acs6G9Ctp8O8QEyJxcUkvkbUTq2pEyjpEc42IjN840bxsOwwLXPtUxfmfgdHMgke5cJr1l7qGqI9i3/TZr/XSxw1O9sO10wnvR95M5ahkX9gcLxXO/6NqP6e2yStbttk/h/4fU+dQ20GQz7uKaOa/+v/qzKwCeZevJCXeldrgMrWDEjrY/NH6yrncGHa9rmclVO70vqS4JPVR9Q==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

