apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgC51NPdf79a8ebnOonyPMbJvtLDmff2WhgF29sF02/AcTNAnj1e7F7uZwo6sYNhwLc6U0r8T7+nVszecQeg2gNzh+aMi153XdFnNjPTjzTcQvxh8TGkRZW+VSsbE95us52hiUizF+83/3R0rssRFrLjkWZqa9wp5NDKJOdWiRrYf+BbjAx1cjBgftyYwMe2CIlqvSaE5Bf3Zmy0oKlPra8V1x3UFMVOr9DeOr+MnRv1OLsd3fDuEemQILoNq1Fv5wvloZHRh1Pw62kkS0YAgr02eGKlr9BZrUrkJkeUa4ySC/OWMjduTQlVbvL+TqZkuLosrNv+0wiWeWLthxTLZGO+D0+oXF08vPwUQsmiz+UZ3mx2ArkRXSsSY33BNaR0gYVyq4q8m0Elu516iOztQjXwvrGTHo9OdFl1it7KTH2bSlDgPJyzGnHm8WSDJOL6o7tcsxkwUfZs/Qo15R29iYdTHmon5HneFnY83WDDWLvUPpMak5vhCnqLOJ4fyy01qG5nNAJrFSkF8BKYe0Qx8mti10GFx6MLTeCDgizT+IbxlNmK2FNsYIng7pfr10oh0deCjGVHUFgUuNAy6IiLwjHEObUq75MX/uZbyyXGnSEmyK6zpVtsWASlnMzydEWtocPatNxEll7o1H8fCAG4gWz7ziW36DzBU12mex1ErxO94cl0UesWP1DWtDH66xu61ugas/8ip7+V6N/+uBX0wWp+DW39MU2WdKoVZGxXtGLhchyPaujoUSFNpksW7sm419YyKTv6s1+ZSiHRHjj6JhHSMREPPThDCDV8dGftyQmXjD9capIkId/PdRVo6ZBo7skKabDUTC2Ij1BPbTRCNPFDz+R7mg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

