apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA6izJX81KtwcXk3yKXM2IqDT292cRFL3XQaeNqyhVEXdtwF+mlsRZLH/3rNuqV3cOo+Z/1+wzlz1IbNx0i0/LXmJLHWMoyIAVU1IwqB3kWEo8hsT9dKCShXI0asDnCcN/u4ugoxa+Mu3/ZxtglWMh9Tv1EpY+QYR36cjQ1moQwbZDrnS8fkp5UID60+z2O3QiTZhbWhn3eQMND2dWitN9EGaU6t8JwlHrcXR98EILZf+fmTCvASz7scNVJCpcBeffGGCrWagjssagdAXUOxQk6dPDQ2NRJngZzGn1AlDXAnw2xe3mRz2JFyEna/7xcKj/4jnlChg3jFq1UX/Tbz0oQGH4LKNJIWzUDms/ePl6R/u2tb/dAMsAN4Fuj1OUf2rGVRrnKUyLCiXZV5MG9dVU3ZQztmiNIdhmC6GWfUTC6r6wxNuxRt117ESIfpNk94wq4lhySnRK4p0/RxwbP2Y4qZyzzTUmNw2XG1nvAmGFxlhljwDyRbkxr6hX7VRuECRUFeqDb9M7MDIwezHc3GkCFSPQIja9ipoQ0vQiJZHdeHJwf+r6JwIcBEArmD3uo2JVFJ8H7hGn0wxyNBCzeP7IyepLnnXPJoC3F4pPBw+gLHI60OHDazY9Bks7pDibJcqoVeReGQ+4rphdhCyKair/Wls4bTkXUIXiby/cG+3J6qo0FOoa9kbANFNHT3BHsd8nJal+t5JF8V66eBwKHrZGfqE+aM7T5wZGtiovduzfsqO/1b9qCO+wbCT/Rk5dYf1Zw8mpnfNWi+DnhZMFel+O+im0epH9Jt/OdddUStrG0icrhcMc/r1fhgjYh2BEPWg5Xn7pR/oCEVPHHtXW/GFHR5d6jgw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

