apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAZAq17XVsaCyBihnBZxFY25kpizU4UbPgf/l5H6kA88lgWsr9LbE0mpCm6OCNiCqL2Vcog96I/qdRaCO3vkmxJb3Rzf4Xx0PvYQe6fsX0mSkJ4eSi8RKx6iIN1CWsDHRvgI7OtnjtziTKYVzGuor6YzOT7iSurN61I23+r0SCFZiXjZ9nuB4C3++Ds6mCkYZMum7lvIoK1toHE+y/JDa4P8RKeNhqddiTtPU+dSyTCg5HyEo68GT4UY+sJNw6BqiGbaTa4Zapi7c8uNbcZVr7A5vfstI57WDNGTACvvVqlNwQxXWIgIqusbZHwFBKy19NbdDFfj7r4jWIMuf7pfNLyuVczdd9JCYRVvKLbf/EmBT+BZ1Vj0o9sckFo5KLFldGlz4AtjIjoY+uOjvGCeJKz0+3BCe9nSbqgrE4EEjAorP8DbSsNFP95SPqnpzSuwpNR+q0RIaKJxdbG/n2KgJrc0CMpBbBgEM/RQr7VNe3vHpqtQ2y9MoHA5mPNsG1MsvvpAe57yR8rd/86w53ed57onZ4gutLpuF3JlvR4VivX/S23r2Lun9L8yup+hXeIOHi6gTN0OMXffzawD0xUCe7P/SXq2gALD6zIak1yAOAs30WVxG59p9mCxMSFN28FzFJ/kwd41ersUmmT0YgkucmqokgYv4jMSvhZTJnUgupU4IDi+2G09y6qgMdLuZqanePBosNRcdWoHoqulshUfPjjyS5mg5QuBb+dICBjyDew8SyIwQQKCEz9webaJ5/pMD/lwc9YhKIMK37qHyD7bnPutLfMHXq9LRc3TEKCxRwtnFpsarX5QUCu4XV4H15Ntqfqa3pgtV5No8UvaLbyCagMBO2gFA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

