apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAtMgswQGI7s5m98+B7tJsPNAiBKSUP/o9AVHaASyoeJf0hO12Cfd0hQoxJicuOgbmFIkUvg1oYcUtOR/7wexgtc8/8YE6M9tllnbfHDuYiT+0os2uDGKvn1SumvPQoi0RyEjoJUloC7fetejoCDxq69/QpM8eM9qYOnBH14BRHZqaNUIpqRXez4JkO0i0+THdMHk9a4QHrzAB5mpadT9mv4+InhPSsnGWYe5VhQzYG5zwZ1nwkzr0py76iiQSWMQWUPal6MIzs6SybaeXUiVoXEB6Huu7N4wz3rxy1Agx2Tzl8oit/lGHpV83l4VCJf8v+3WWCd2pMqfunGL2zUZaYdUZebcTGnEBoeU0CNk067j/1p3CwygZu+xVHVjARNGuGNYAk5GzEanGhqpctVpWjMeXnsdnrX8lh+YYDIOt749E7PYY+kUxIqWjO6nkPs8abwdt5Uac/OZtOwihU/7ryrkCuHuOChdj4HGPIVLX9xgqqsqSd3WOxcNv0AfTM0rjMQATANpzXFNORjHCfU1QyL/g17SQ6ZkAuBrdd+gAj93lAfyRW7hoC4nTa861S9rwP+gC+jpbv+d6wYOqtqJeqJmVgUKZQ+aPq7MeA3TCN9+nR1pV/S9h3LRTAHuqnmVaqwgT2mTxFyd7LgxjVxPmQgvATAHv4duWNiccEEBD8UgOwngkTKtl4pyHXQWznqreXd4y/XIWZkjGvbiG3CpGbHxyf8z60jTzIop2KQhb0krQnvhHCPhHkYolQWYMyYBMyKMmevb1uKLVqkGKtCBS1NNpdySvTObPrbYzfl0vh0zAPKNFsLevHCXg7PuCNAFURDQz6H8QYaB+JBBHL5p1L7qQSKQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

