apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBj5oxmbAsKXAE6XtIuz/IpIE5FT3IOHwq7Yc7aMQJU9mZS4GA/3BmGq//6y7451X2mjIYNlDAc/Lu3sVVmQPNELsSMKspC1eo8M5Psb31auWOHvC9fJ46pv6xuwHDsCatZg478hRqGLpop7mDW//1SkJIFZiIeAoclqb8m4SIk4MRzJKCZMoLkf43mQrGtxT0pOugWzY2yfPKONAJBL/KpH6uC2zkmuvQGiBMSMQIME7hb92rBwQboilsaxR/eWJ2p2sgntzBabUG/Q/ndzA9wNkdcufk0P5uNtb8M2eZeISkAHeNK4l102rMlln1PBeOQBwi9+pzpus8/gzuCISZrH1MZgkNh249Dsgiy7Lwp5ateoS8Cm8jMAoyFZE1FxWqIYG4dQBh9jbQL9y511PhaLbMTQtPQhoVSV10nHwdD7v0pLhi91I5CMD80nIYqQV0w8yJIZJZIF3/Y+J3PS96lv3y3tILk/HsDr6QQjhcU77fFRQI6kb0LhRn3ZornVfml6Pkza84xxpsjGcCt+KYD3k8U313fMOUZYWDxzGQAwXB5XYK6b+IaFOmADncaTNF7ZafgHqwHxDrRtxF1kuMnCVBvD3yYi2kSvQ8yRuR9WI6/K+4+FDUxZFpVxSYGbJFxDXBrkzCv83AdnYUU+hOrUnVEqXgNKbcXO7vzFdR3oNIrf2YuyjBvoxfjPMZNa2ApRqU7d8222f6Ev3jz5WJ9bsua5JbR2Q3BsjgEPjnseC6sY2Ce+ZwcVY8Yldtnq8yjie4xlrRSHXh6MSyeFXJ5gT01oyygZxIANwZvYQnLsUYdHnwze1MATfX/7S80lB0SSnjSGZ5pa+OXGCZEXQ18CUuVGA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

