apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAbo4R5c/nUa3V4hOzHUx61xfgbZRGpug5nplRkVFKgSC0lwAXwdkyawReNoOaZx9e1DP/8kUuNDKQnGuayIur6WJ9ZeoeSzMopG0yQITbgbe6UBEUUrakGlish8JPB0CqvQpmWQXQo/ZuV6I03zUPuFl20HMT8Im30p48URA6BuIFhb1YpqYlHB5zbdvSQ3VuB3EVaGxmj/C1+IFu/y2miG3Ey7VY1AXMhk/YPxlMwytvBNkUhKATz9e8jXzfR1URUVDvtDvmgVLd2U0LGu+Cpp5yiU9oTh/7ipaLmQsdg7hhktBZtfg+qd0V/y//ayXTQhBWZb4XkA0Jt4JRAZ2l8ygdLhZ9UHNpEOE5btJEr//tgQYDnqWNW6rjv9SVdo6QqdcZEWATbgiFk9OuTOZ9L2qCcHmzrhgFi2lNC6HzWSs0Q1fAmV+FIxseTyuUPlRKiOYU16LdmDywFnNrXDIesnmQLcTXDUwef+c0MPfZqUgYlJ8RjXyVtzOF93WDWqIzjAf7sn6vBAae3Az5ZT2NVhB2x8KfWuDWzd8vtTP5WQvx/CkmR6UiiXEr5gl7jMVUhWmOPF/OZ3tKzLOKvlwdNmMHVRpMA1elJ7sC3P9tDaOK1vkr0Tho8rTVs2IW3Sawez04eGCogIAOQimIox+ok/P3dwpV05yits7UBElczSsZy6mgFc0kORiYR7/OtZoUvhATWam/U6rbJAoGD/OYrObYH+ePegtZcJAkc4uk8FFGyHT6YokKKU0cxpW0g/QdEQvScDW2aI4cKGonzcB9La9UEShRv/21dfeDR1SM7P0sUb5cnNKbL8pF4EEkIT83zCxj6oFlP/c/1IFBHPvBmhEEtgQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

