apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA4X2QwxDYoacBSpOUvopotjxKvtK4IUqFtyOT+6Ko2nNpS1xLEpYudQUDJJAuA1OXVZWhpLOP/286xsNzfxjPf/1cf+Y+1cGBzNb5Oer9pMId13A6HHWKY4Vo9vEbaZkBQSIXaQ1Xcnwehu+cIFJbKMeaCoFw1sGsScfQ9wDbsouVAKScHms3EiKmpPkV1uuWIus97aSggdrhMxHUUZ8EPpyIwqRxWrKX/18rxC3SoQ38MHY0ZkJO2cg+ZCleTO8429thgUr+zYTVZNOa2DsKeKNfKm1G3CXPnuH5oEO+E7jfuzFRzlmvGAW989yhNNlwhueuMvRwHr/lREhlhXG57Oy651GYRgBEoFTSOZB8mu3HxeXwjSkBL4OTO3P4LZQehxY7O959957/vYBJJ3UCxpOAytvJVIC1KR9o1SEPSPbd38QJdBOv6W5Cj9rs0GOKBmR8zvo2Oc62xAijEvVbRKQuFh3XmyfE9ZLCQbEirM3Q6Hnl8KZuYizN2Dg330oROKabPvCFPy8oclSzI4iguSaJ8tE64HtenHTf3sZcveM12Y4HjP0edINBbKms1OhNQ1aihMGqtw82YqMuQxyyYHYsAvx19sDhWXz1hpssRbIKUtnJiy7MMq/JdStpfNk+9Z1mBGykBrUxUZT345u0CtVKpe89amnknsCBt3WBci4fb4VIYDodSV+i1vCGaucIlxhhjlDZkVyj0k5erNpxj0oZDxN1a+FchTyG9dmB9FXNL8fOw29z+O4PL6P4FDlzJQJnZcQv75abB1A/tgOB3KhBt2NHJpWTxiGULeFWeKNQYsPaUQCswBiHTIdgrV/vbP0nn+LRFM/yVgeBgMCWeHIGaKw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

