apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: task-tracker-app-ui # name of the k8s service
spec:
  hosts:
  - staging.mlops-playground.com
  - task-tracker-app-ui.staging.svc.cluster.local
  gateways:
  - default-gateway
  http:
  - match:
    - uri:
        exact: /task-tracker
      gateways:
      - default-gateway #restricts this rule to apply only to ingress gateway
    route:
    - destination:
        host: task-tracker-app-ui
        port:
          number: 8000

 
