apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-service.yaml
- namespace.yaml
- ../../base

namespace: staging
images:
- name: foxy7887/task-tracker
  newName: foxy7887/task-tracker
  newTag: bdb1ce0f7f0d7a04b1106db396578e7c0cdefbaa
