apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-service.yaml
- namespace.yaml
- ../../base

namespace: staging
images:
- name: foxy7887/task-tracker-app
  newName: foxy7887/task-tracker-app
  newTag: v32
