apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: istio-system
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: tls-cert
  dnsNames:
  - staging.mlops-playground.com
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: istio-system
spec:
  ca:
    secretName: tls-cert