apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: tls-cert
  dnsNames:
  - '*.mlops-playground.com'
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "cert-manager-tls=local" # Sync certificate to matching namespaces  
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: istio-system
spec:
  ca:
    secretName: tls-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer2
  namespace: local
spec:
  ca:
    secretName: tls-cert
