apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-aws
  annotations:
    guide: quickstart
    provider: aws
    vpc: default
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.15.0"