apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base

namespace: mlflow

configMapGenerator:
- name: mlflow-configmap
  behavior: merge
  envs:
  - .env
  

