apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-s3-
  namespace: workflows
spec:
  entrypoint: train-workflow
  serviceAccountName: workflow
  templates:
  - name: train-workflow
    dag:
      tasks:
      - name: preprocess
        outputs:
 	        artifacts:
 	          - name: output
	            path: /tmp/output.csv

      - name: train
        dependencies: [preprocess]
        template: train
        arguments:
          artifacts:
            - name: data
              from: "{{tasks.preprocess.outputs.artifacts.output}}"
          parameters:
            - name: outfile
              value: "iris-xgb.pkl"
  - name: preprocess
    outputs:
      artifacts:
        - name: output
          path: /tmp/output.csv
    container:
      name: preprocess
      image: foxy7887/xgb_train:v5
      command: ["python3", "./run_preprocess.py"]

  - name: train
    inputs:
      parameters:
      - name: outfile
      artifacts:
      - name: data
        path: /tmp/input.csv
    container:
      name: train
      image: foxy7887/xgb_train:v5
      command: ["python3", "./run_train.py"]
      args: ["--model_file", "{{inputs.parameters.outfile}}", "--bucket", "test"]
    outputs:
      artifacts:
      - name: model
        path: /tmp/model
    


     # inputs:
    #   artifacts:
    #   - name: my-art
    #     path: /datasets
    #     s3:
    #       endpoint: minio.default:9000
    #       insecure: true
    #       bucket: my-bucket
    #       key: my-bucket/data/
    #       accessKeySecret:
    #         name: argo-artifacts
    #         key: accesskey
    #       secretKeySecret:
    #         name: argo-artifacts
    #         key: secretkey