apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-configmap
data:
  ARTIFACT_STORE: <URI OF THE GOOGLE CLOUD ARTIFACT STORE>
  PG_DATABASE: "mlflow"
  PG_HOST: "postgresql.default.svc.cluster.local"
  PG_PORT: 5432