apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-server
  namespace: mlflow
  labels:
    app: mlflow-tracking-server
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: mlflow-tracking-server
