apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-container-image-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: build
  serviceAccountName: default
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred # .spec.volumes[].secret.secretName field equal to the name of the Secret object.
      items:
        - key: .dockerconfigjson
          path: config.json   
  templates:
  - name: build
    dag:
      tasks:
      - name: build
        templateRef:
          name: container-image
          template: build-kaniko-git
          clusterScope: true
        arguments:
          parameters:
          - name: app_repo
            value: git://github.com/davidfox87/task-tracker
          - name: container_image
            value: foxy7887/task-tracker-app
          - name: container_tag
            value: "v2"
          - name: sub_path
            value: frontend

