apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: my-eks
  annotations:
    meta.crossplane.io/maintainer: David Fox
    meta.crossplane.io/source: github.com/vfarcic/devops-toolkit-crossplane/tree/master/packages/gitops
    meta.crossplane.io/description: Fully operational GitOps tools Argo CD
    meta.crossplane.io/readme: A Configuration package that defines GitOps and GitOpsClaim types that can be used to provision Kubernetes clusters with fully operational GitOps tools Argo CD and Rancher Fleet
spec:
  crossplane:
    version: ">=v1.4.0-0"
  dependsOn:
  - provider: crossplane/provider-aws
    version: ">=v0.29.0"
  - provider: crossplane/provider-helm
    version: ">=v0.9.0"
  - provider: crossplane/provider-kubernetes
    version: ">=v0.4.0"