# The example below creates a certificate resource in istio-system namespace. 
# This in turn creates a secret cert-secret.
# sync a certificate belonging to istio Certificate from the cert-manager 
# namespace into the staging namespace

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-secret
spec:
  secretName: cert-secret # tls-secret belongs in staging namespace but we want to sync it to istio-system namespace
  commonName: staging
  issuerRef:
    name: staging-ca
    kind: Issuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "cert-manager-tls=test2" # Sync certificate to matching namespaces