apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
spec:
  selector:
    matchLabels:
      app: mlflow-tracking-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-tracking-server
    spec:
      containers:
      - name: mlflow-tracking-server
        image: foxy7887/mlflow:v4
        imagePullPolicy: Always
        args:
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=postgresql://mlflow:mlflow@postgres:5432/mlflow-db 
        - --default-artifact-root=s3://artifacts/
        - --workers=2
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: db-secret
        - configMapRef:
            name: mlflow-configmap

