apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-server
  labels:
    app: mlflow-tracking-server
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    #name: mlflow-tracking-server
  selector:
    app: mlflow-tracking-server
