apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
  - pv.yaml
  - nodeport-service.yaml


namespace: minio-nodeport


patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: minio
    path: deployment-patch.yaml

