apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  labels:
    app: storage-nodeport
spec:
  type: NodePort
  ports:
    - name: minio-http
      port: 9090
      targetPort: 9090
  selector:
    app: minio
